# Generated by Django 4.1.4 on 2023-01-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzados',
            name='size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
